---

- name: Set linux version fact on Debian based distros.
  ansible.builtin.set_fact:
    motd_linux_version: "{{ ansible_lsb.description | regex_replace('^.* ([\\d\\.\\-]+).*?$', '\\1') }}"
    motd_linux_distribution: "{{ ansible_lsb.description | regex_replace('^([\\w\\/\\s]+) [0-9]..*?$', '\\1') }}"
  changed_when: false
  when: ansible_os_family == "Debian"

- name: Install /etc/issue and /etc/issue.net.
  become: true
  ansible.builtin.template:
    src: "{{ ansible_os_family }}-issue.j2"
    dest: '/etc/{{ file.name }}'
    owner: root
    group: root
    mode: '0644'
    backup: '{{ issue_banner_backup }}'
  loop:
    - name: 'issue'
      content: '{{ issue_banner_msg }}'
      version: '{{ motd_linux_version | default([]) }}'
      distribution: '{{ motd_linux_distribution | default([]) }}'
    - name: 'issue.net'
      content: '{{ issue_banner_net_msg }}'
      version: '{{ motd_linux_version | default([]) }}'
      distribution: '{{ motd_linux_distribution | default([]) }}'
  loop_control:
    loop_var: file
