---

- name: set linux version fact on Debian based distros
  set_fact:
    ansible_role_motd_linux_version: "{{ ansible_lsb.description | regex_replace('^.* ([\\d\\.\\-]+).*?$', '\\1') }}"
    ansible_role_motd_linux_distribution: "{{ ansible_lsb.description | regex_replace('^([\\w\\/\\s]+) [0-9]..*?$', '\\1') }}"
  changed_when: false
  when: ansible_os_family == "Debian"

- name: install /etc/issue and /etc/issue.net
  become: true
  ansible.builtin.template:
    src: "{{ ansible_os_family }}-issue.j2"
    dest: '/etc/{{ file.name }}'
    owner: root
    group: root
    mode: 0644
    backup: '{{ ansible_role_motd_backup }}'
  loop:
    - name: 'issue'
      content: '{{ ansible_role_motd_issue_msg }}'
      version: '{{ ansible_role_motd_linux_version | default([]) }}'
      distribution: '{{ ansible_role_motd_linux_distribution | default([]) }}'
    - name: 'issue.net'
      content: '{{ ansible_role_motd_issue_net_msg }}'
      version: '{{ ansible_role_motd_linux_version | default([]) }}'
      distribution: '{{ ansible_role_motd_linux_distribution | default([]) }}'
  loop_control:
    loop_var: file

